steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helloworld']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
    - 'run'
    - 'deploy'
    - 'helloworld'
    - '--image'
    - 'gcr.io/$PROJECT_ID/helloworld'
    - '--region'
    - 'us-east4'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
images:
  - gcr.io/$PROJECT_ID/helloworld